# Generated by Django 6.0 on 2025-12-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housepriceprediction',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
